name: Build Images
run-name: ${{ github.actor }} building images

# trigger manually
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Registry
        uses: docker/login-action@v3
        with:
          registry: hub.ar5.in
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
          
      # Build Image
      - name: Build App
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/common/php-fpm/Dockerfile
          push: true
          tags: hub.ar5.in/rolify/app:0.1.7-test
          target: production
          
      # Build Image
      - name: Build Web Server
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/staging/nginx/Dockerfile
          push: true
          tags: hub.ar5.in/rolify/web:0.1.7-test
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Test SSH to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}  # e.g., your VPS IP or hostname
          username: ${{ secrets.SERVER_USER }}  # e.g., root or your Debian user
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # SSH private key content
          port: 22
          script: |
            export IMAGE_TAG=0.1.7-test
            docker stack deploy -c ${{ secrets.STAGING_PATH }}/docker-stack.yaml --with-registry-auth -d rolify_stg
