name: Deploy to Staging

on:
  push:
    branches: [develop, staging]
  pull_request:
    branches: [develop]

jobs:
  
  deploy-staging:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/staging'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup SSH
      uses: webfactory/ssh-agent@v0.9.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Staging Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << 'EOF'
          cd ${{ secrets.STAGING_PATH }}
          
          # Pull latest changes
          git pull origin develop
          
          # Install dependencies
          composer install --no-dev --optimize-autoloader --no-interaction
          
          # Install Node dependencies and build assets
          npm ci
          npm run build
          
          # Laravel optimizations
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan event:cache
          
          # Run migrations
          php artisan migrate --force
          
          # Clear application cache
          php artisan cache:clear
          
          # Set permissions
          chown -R deployer:www-data storage bootstrap/cache
          chmod -R 775 storage bootstrap/cache
          
          # Restart services (disabled temporarily)
          # sudo systemctl reload php8.3-fpm
          # sudo systemctl reload nginx
        EOF
      
