name: Test App
run-name: ${{ github.actor }} testing the application

on:
  # Trigger manually
  workflow_dispatch:

jobs:
  tests:
    name: Run Test Suite
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: mbstring, dom, sqlite3, pdo_sqlite
          coverage: none

      - name: Validate composer.json and composer.lock
        run: composer validate --no-check-publish

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist

      - name: Prepare environment
        run: |
          cp .env.example .env
          php artisan key:generate --ansi

      - name: Run tests (Pest)
        run: |
          vendor/bin/pest --colors=always --ci
